### sample sheet ###
sample_sheet: "config/sample_sheet.csv"


### modules ###
readqc: FALSE
readanalysis: FALSE
assembly: FALSE
coassembly: TRUE
binning: FALSE
binning_coassembly: TRUE
contiganalysis: TRUE