Packages

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(data.table)
library(dtplyr)
```


Sample data frame
```{r}
sample_dates <- data.frame(sample = c("CAN1", "CAN2", "CAN_1", "CAN_2", "CAN_3", "CAN3"),
                              day =c(451, 521, 549, 612, 671, 728))
```

Reference file and annotations
```{r}
ref <- fread("/projects/b1052/mckenna/resources/diamond/denit_uniprotkb.tsv", sep = "\t")
colnames(ref) <- c("entry", "entry_name", "protein_names", "gene_names", "organism", "gene_length", "reviewed")
ref <- ref %>%
  select(-reviewed)

get_ann_by_sample <- function(sample){
  ann_file <- paste0("./results/diamond_contigs/", sample, "/uniref90_denit.tsv")
  ann <- read.table(ann_file, comment.char = "#", 
                      col.names = c("qseqid", "sseqid", "pident", "length", "mismatch",
                                    "gapopen", "qstart", "qend", "sstart", "send",
                                    "evalue", "bitscore")) %>%
  separate_wider_delim("sseqid", "|", names = c("tr", "entry", "entry_name")) %>%
  select(-c(tr, entry_name)) %>%
  separate_wider_regex("qseqid", c(contig = ".*", "_", num_on_contig = ".*")) %>%
  filter(pident >= 70) %>%
  left_join(ref, by = "entry")
  return(ann)
}

ann_list_all <- lapply(setNames(sample_dates$sample, sample_dates$sample), get_ann_by_sample)


rm(ref)

```


Get depth by sample - read in rpkm file and join to ref+annotation df
```{r}
get_depth_by_sample <- function(sample){
  depth_file <- paste0("./results/pileup/", sample, "/", sample, ".rpkm.txt")
  depth <- read.table(depth_file, comment.char = "#", 
                         col.names = c("contig", "length", "bases", "coverage", "reads", "rpkm", "frags", "fpkm")) %>%
    select(-c(length, bases, frags, fpkm))
  df_depth_ann <- ann_list_all[[sample]] %>%
    left_join(depth, by = "contig")
  return(df_depth_ann)
}


depth_list_all <- lapply(setNames(sample_dates$sample, sample_dates$sample), get_depth_by_sample)

rm(get_depth_by_sample)
```


Summarise depth by organism and protein name
```{r}

get_depth_summarized <- function(depth_list){
  df_summary <- depth_list %>%
    group_by(organism, protein_names) %>%
    summarise(sum_rpkm = sum(rpkm))
  return(df_summary)
}

depth_list_summary <- lapply(depth_list_all, get_depth_summarized)
names(depth_list_summary) <- sample_dates$sample

saveRDS(depth_list_summary, "./notebooks/data_files/depth_list_denit_summary.RDS")

rm(get_depth_summarized)

```


Separate to relevant PAO and GAO
```{r}
get_depth_pao_gao <- function(depth_list){
  df_summary <- depth_list %>%
    filter(str_detect(organism, "(?i)accumulibacter|competibacter|tetrasphaera|dechloromonas|contendobacter|defluviicoccus|plasticumulans|thauera|zoogloea|flavobacterium"))
  return(df_summary)
}

depth_list_pao_gao <- lapply(depth_list_summary, get_depth_pao_gao)
names(depth_list_pao_gao) <- sample_dates$sample

saveRDS(depth_list_pao_gao, "./notebooks/data_files/depth_list_pao_gao.RDS")

rm(get_depth_pao_gao)

```


Return a single df and delete preceding files
```{r}
depth_pao_gao <- bind_rows(depth_list_pao_gao, .id = "sample")

rm(depth_list_all, depth_list_summary, df)

```

Cleaning

```{r}
## saved this to an excel file for manual review

depth_pao_gao_clean <- depth_pao_gao %>%
  mutate(organism_clean = case_when(str_detect(organism, "(?i)accumulibacter") ~ "Accumulibacter",
                                    str_detect(organism, "(?i)competibacter") ~ "Competibacter",
                                    str_detect(organism, "(?i)tetrasphaera") ~ "Tetrasphaera",
                                    str_detect(organism, "(?i)dechloromonas") ~ "Dechloromonas",
                                    str_detect(organism, "(?i)phosphoribacter") ~ "Phosphoribacter",
                                    str_detect(organism, "(?i)contendobacter") ~ "Contendobacter",
                                    str_detect(organism, "(?i)plasticumulans") ~ "Plasticumulans",
                                    str_detect(organism, "(?i)Defluviicoccus") ~ "Defluviicoccus",
                                    str_detect(organism, "(?i)flavobacterium") ~ "Flavobacterium",
                                    str_detect(organism, "(?i)thauera") ~ "Thauera",
                                    str_detect(organism, "(?i)zoogloea") ~ "Zoogloea")) %>%
  group_by(sample, protein_names, organism_clean) %>%
  summarise(sum_rpkm = sum(sum_rpkm)) %>%
  pivot_wider(names_from = "sample", values_from = sum_rpkm)

write_csv(depth_pao_gao_clean, file = "./notebooks/data_files/depth_pao_gao_clean.csv")

```
